import { Geist, Geist_Mono } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { Providers } from "@/store/provider";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/Auth";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "DoodleWar - SpeedUp your drawing!",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                {" "}
                <Providers>
                    <AuthProvider>{children}</AuthProvider>
                </Providers>
                <ToastContainer toastClassName="custom-toast" />
            </body>
        </html>
    );
}
